### ISSUE TITLE
La légende de la carte est dupliquée

### ISSUE THREAD

**Issue by fabienheureux** [incubateur-ademe/quefairedemesobjets#938]
En mobile et en desktop on affiche deux choses différentes 

Cela pose plusieurs problèmes 
- Du code javascript/stimulus est dupliqué pour gérer l'état 
- Cela génère du contenu dupliqué dans le html - pas fou niveau accessibilité 
- Pour la maintenabilité, d'une manière générale on préférera ne pas dupliquer de codes 

# Screenshots 
## Mobile 
![image](https://github.com/user-attachments/assets/ef8fe211-a7a8-48e3-bfad-72dd05dc7ea9)

## Desktop
![image](https://github.com/user-attachments/assets/159fc1c7-00ec-448b-b8a6-777fc6b30f68)

---

# TODO 

- [ ] Supprimer l'une des deux versions 
- [ ] Tout uniformiser dans un seul contrôleur stimulus 
- [ ] Gérer le style en mobile et desktop avec un seul élément dans le DOM
